#!/usr/bin/env python3
"""Pull tracked time for the CBHS project from Solidtime and write index.html.

The page is fully static - the token stays in the environment and only day
figures reach the HTML. The budget is the sum of the per-task caps
below.

Usage:
  set -a && . ./.env && set +a
  python3 scripts/gen_progress.py

Standard library only.
"""
import html
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from datetime import datetime
from zoneinfo import ZoneInfo

BASE_URL = os.environ.get("SOLIDTIME_URL", "https://solidtime.zestdev.uk")
TOKEN = os.environ.get("SOLIDTIME_TOKEN", "")
PROJECT_NAME = "CBHS 2026 Website"
HOURS_PER_DAY = 7.5

# Day caps per Solidtime task, matched by exact name. Tasks not listed here
# still get a row, showing tracked time only.
CAPS = {
    "CBHS - Website - Release 1": 7,
    "CBHS - Website - Release 2": 10,
    "CBHS - Website - Support": 3,
    "CBHS - Website - Measurement": 4,
}

# Tasks left off the page. Their time still counts towards the total.
HIDDEN = {"CBHS - Briefing Time"}
OUT = os.path.join(os.path.dirname(os.path.dirname(
    os.path.abspath(__file__))), "index.html")


def api(path, params=None):
    if not TOKEN:
        sys.exit("SOLIDTIME_TOKEN is not set.")
    url = BASE_URL.rstrip("/") + "/api" + path
    if params:
        url += "?" + urllib.parse.urlencode(params, doseq=True)
    req = urllib.request.Request(url, headers={
        "Authorization": "Bearer " + TOKEN,
        "Accept": "application/json",
        # Cloudflare in front of Solidtime 403s the default urllib agent.
        "User-Agent": "cbhs-progress-page",
    })
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return json.load(r)["data"]
    except urllib.error.HTTPError as e:
        sys.exit("HTTP %d on %s\n%s" % (e.code, path, e.read()[:300]))


def days(seconds):
    return seconds / 3600.0 / HOURS_PER_DAY


def fmt(value):
    return ("%.1f" % value).rstrip("0").rstrip(".")


def main():
    org = os.environ.get("SOLIDTIME_ORG") or \
        api("/v1/users/me/memberships")[0]["organization"]["id"]
    projects = api("/v1/organizations/%s/projects" % org)
    project = next((p for p in projects if p["name"] == PROJECT_NAME), None)
    if not project:
        sys.exit("No project named %r" % PROJECT_NAME)

    # done=all so finished tasks still resolve to a name.
    tasks = api("/v1/organizations/%s/tasks" % org, {"done": "all"})
    result = api("/v1/organizations/%s/time-entries/aggregate" % org,
                 {"group": "task", "project_ids[]": project["id"]})
    seconds = {r["key"]: r["seconds"] for r in result["grouped_data"] or []}

    # Every task in the project gets a row, even before time is logged on it.
    rows = [(t["name"], days(seconds.get(t["id"], 0)), CAPS.get(t["name"]))
            for t in tasks if t["project_id"] == project["id"]
            and t["name"] not in HIDDEN]
    missing = set(CAPS) - {name for name, _, _ in rows}
    if missing:
        sys.exit("Capped tasks not found in Solidtime: %s" % ", ".join(missing))
    if seconds.get(None):
        rows.append(("Other", days(seconds[None]), None))
    # Capped tasks first, in CAPS order, then the rest by time tracked.
    order = list(CAPS)
    rows.sort(key=lambda row: (order.index(row[0]) if row[2] else len(order),
                               -row[1]))
    tracked = days(result["seconds"] or 0)
    budget = sum(CAPS.values())

    write_page(tracked, budget, rows)
    print("tracked %s / %s days" % (fmt(tracked), fmt(budget)))
    for name, d, cap in rows:
        print("  %-30s %s%s" % (name, fmt(d), " / %s" % cap if cap else ""))


def bar(value, total):
    pct = min(100, value / total * 100) if total else 0
    return '<div class="bar"><span style="width:%.1f%%"></span></div>' % pct


def write_page(tracked, budget, rows):
    updated = datetime.now(ZoneInfo("Europe/London")).strftime(
        "%-d %b %Y, %H:%M %Z")
    headline = "%s of %s days used" % (fmt(tracked), fmt(budget))
    sub = "%s days remaining" % fmt(max(0, budget - tracked))
    task_rows = "\n".join(
        '<li><div class="row"><span>%s</span><b>%s%s d</b></div>%s</li>'
        % (html.escape(name.removeprefix("CBHS - ")), fmt(d),
           " / %s" % cap if cap else "", bar(d, cap or tracked))
        for name, d, cap in rows)

    page = TEMPLATE.format(headline=headline, sub=sub, updated=updated,
                           total_bar=bar(tracked, budget),
                           rows=task_rows)
    with open(OUT, "w") as f:
        f.write(page)


TEMPLATE = """<!doctype html>
<!-- Generated by scripts/gen_progress.py - do not edit by hand. -->
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>CBHS Website Progress</title>
<style>
  :root {{ --accent: #f58220; --text: #1a2238; --mute: #5a6478;
          --track: #eceef2; --bg: #f7f8fa; --card: #fff; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --text: #e8eaf0; --mute: #9aa2b4; --track: #2a2f3a;
            --bg: #12151b; --card: #1b1f27; }}
  }}
  * {{ box-sizing: border-box; margin: 0; }}
  body {{ font: 16px/1.5 system-ui, sans-serif; color: var(--text);
         background: var(--bg); padding: 48px 16px; }}
  main {{ max-width: 640px; margin: 0 auto; background: var(--card);
         border-radius: 12px; padding: 32px; }}
  .kicker {{ font-size: 12px; font-weight: 700; letter-spacing: .12em;
            text-transform: uppercase; color: var(--accent); }}
  h1 {{ font-size: 28px; margin: 6px 0 2px; }}
  .sub, .foot {{ color: var(--mute); font-size: 14px; }}
  .bar {{ height: 10px; background: var(--track); border-radius: 5px;
         overflow: hidden; margin: 8px 0; }}
  .bar span {{ display: block; height: 100%; background: var(--accent); }}
  h2 {{ font-size: 14px; margin: 32px 0 8px; color: var(--mute); }}
  ul {{ list-style: none; padding: 0; }}
  li {{ margin-bottom: 12px; }}
  .row {{ display: flex; justify-content: space-between; font-size: 15px; }}
  .foot {{ margin-top: 24px; font-size: 13px; }}
</style>
</head>
<body>
<main>
  <div class="kicker">CBHS 2026 Website</div>
  <h1>{headline}</h1>
  {total_bar}
  <p class="sub">{sub}</p>
  <h2>Breakdown</h2>
  <ul>
{rows}
  </ul>
  <p class="foot">Last updated {updated}.</p>
</main>
</body>
</html>
"""

if __name__ == "__main__":
    main()
